//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public long StudentID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
    }
}
