//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public long ID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<decimal> Mark { get; set; }
        [JsonIgnore]
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
